GOOGLE_API_KEY="*"

[gcp_service_account]
type = "service_account"
project_id=  "*"
private_key_id= "*"
private_key= "*"
client_email= "*"
client_id="*"
auth_uri= "*"
token_uri= "*"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "*"
universe_domain="googleapis.com"

[gcp]
project_id = "*"
dataset_id = "*"
table_id = "*"
